# site properties and page defaults
title: RIGHT Lab
subtitle: Research at the Intersection of Geochemistry, Health, and Technology
description: Description coming soon.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: rachel-coyte@nmt.edu
  orcid: 0000-0001-6369-5311
  google-scholar: 1ypl6Q4AAAAJ&hl
  github: rcoyte
 # twitter: rcoyte
 # youtube: rcoyte

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
